### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by O-Mutt** [rabbitmq/rabbitmq_auth_backend_oauth#5]
Just wanted to check in on this project. I see in the readme that we are to hold on impl of this, siting a 6 month timeframe. Based on the commit history that may not be quite accurate. Do you have an updated timeline or has this been abandoned as a whole?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
This project is on hold because our team depends on decisions in other projects (mostly in Cloud Foundry but could be other multi-service environments). In other words, if it doesn't work for Cloud Foundry, we are back to the drawing board.

We did explore a few potential implementations and are now waiting for a design from 2 other teams. I have no an ETA on this. You are more than welcome to experiment with what we have (which is definitely quite incomplete) and tell us how it goes on the mailing list. Perhaps that can influence the direction of this plugin as well as its close sibling https://github.com/rabbitmq/rabbitmq-auth-backend-uaa (which is where most of the recent activity has been because we have a specific service to design and develop against).
